### ISSUE TITLE
ETSource should be able to calculate and set preset/expected_demands in the graph

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etsource#168]
With the help of Turbine, ETSource should be able to calculate a graph from a starting situation with technology shares
#### Structure and start data:

![](http://f.cl.ly/items/1Q0M3h3I1l000T3I3S2C/Screen%20Shot%202012-10-26%20at%2012.20.58%20PM.png)
#### Final Demand

Final Demand (631.8PJ, 266.6PJ) see e.g. energybalance/nl.yml in the _ruby_ branch.
#### Technology Shares and Application Split

``` yaml
gas:
  space_heating: 0.73
    gas_heater: 0.1
    combi_heater: 0.9
    gas_heat_pump: 0
    gas_chp: 0
  hot_water: 0.24
  cooking: 0.03
  cooling: 0
```
#### Efficiencies

Of course, efficiencies from the converters should be used to calculate output from input, e.g. when gas_heater is 80% efficient, and LINK(space_heating -> gas_heater = 100), then LINK(gas_heater -> UD_heating_HH) should be 80.
#### Preset and expected_demands

Because of the way the current ETEngine works, it should set _expected_demand_ for all the converters, but _preset_demand_ for the left_most converters (with no parents).
