### ISSUE TITLE
Carrier prices should be stored in human_readable_format so that it will be easy to update them.

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etsource#27]
**example**: 
1. defaults:

``` yaml
:crude_oil:
  - price_in_dollar_per_barrel: 150

:uranium_oxide:
  - price_in_euro_per_kg: 4_000

```
1. nl:

``` yaml
:crude_oil:
  - price_in_dollar_per_barrel: 130

```
